In [2]:
import numpy as np

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [6]:
a = np.linspace(1, 10, 10)
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

2.	Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [8]:
a = np.zeros((3, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

3.	Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [46]:
a = np.random.randint(1, 11, (5, 5))
print(a)

[[ 5  8  5  8  5]
 [ 9  9  3  6  6]
 [ 8  6 10  8  5]
 [ 3  8  8  8  4]
 [ 5  5  1 10  9]]


4.	Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [49]:
a = np.random.random((4, 4))
a

array([[0.07531874, 0.20652514, 0.8751196 , 0.27817171],
       [0.45523136, 0.8907884 , 0.11457488, 0.72207699],
       [0.15627108, 0.30889061, 0.95260298, 0.02169701],
       [0.97574231, 0.61676658, 0.72583763, 0.51884257]])

5.	Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [51]:
a = np.random.randint(1, 11, (5, 5))
b = np.random.randint(1, 11, (5, 5))
print(a)
print(b)
print(a + b)
print(a - b)
print(a * b)

[[10  3  1  3  1]
 [10  9  5  7  7]
 [ 8  1 10  7  4]
 [ 3  8  8  3  2]
 [ 3  2  8  6  5]]
[[ 7  6 10  4  9]
 [ 7  8  2  7  8]
 [ 7  4  6  8  4]
 [ 2  5 10  9  9]
 [ 9  6  8  1  6]]
[[17  9 11  7 10]
 [17 17  7 14 15]
 [15  5 16 15  8]
 [ 5 13 18 12 11]
 [12  8 16  7 11]]
[[ 3 -3 -9 -1 -8]
 [ 3  1  3  0 -1]
 [ 1 -3  4 -1  0]
 [ 1  3 -2 -6 -7]
 [-6 -4  0  5 -1]]
[[70 18 10 12  9]
 [70 72 10 49 56]
 [56  4 60 56 16]
 [ 6 40 80 27 18]
 [27 12 64  6 30]]


6.	Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [58]:
a = np.random.randint(0, 10, 7)
b = np.random.randint(0, 10, 7)
print(a, b)
print(np.dot(a, b))


[5 9 8 6 7 5 0] [9 0 6 9 5 2 9]
192


7.	Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [16]:
a = np.random.randint(1, 11, (2, 2))
b = np.random.randint(1, 11, (2, 3))
print(a)
print(b)

print(np.dot(a, b))



[[2 1]
 [9 9]]
[[2 3 4]
 [5 2 7]]
[[ 9  8 15]
 [63 45 99]]


8.	Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [13]:
a = np.random.randint(1, 11, (3, 3))
a_inv = np.linalg.inv(a)
print(a)
print(a_inv)

[[ 6 10  5]
 [ 1  4  1]
 [10  3  3]]
[[-0.14754098  0.24590164  0.16393443]
 [-0.1147541   0.52459016  0.01639344]
 [ 0.60655738 -1.3442623  -0.2295082 ]]


9.	Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [15]:
a = np.random.randint(1, 11, (4, 4))

print(a)
print(a.T)

[[ 9 10  5  3]
 [ 5  3  3  1]
 [ 7  8 10  3]
 [ 9 10  8  2]]
[[ 9  5  7  9]
 [10  3  8 10]
 [ 5  3 10  8]
 [ 3  1  3  2]]


10.	Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [18]:
a = np.random.randint(1, 11, (3, 4))
b = np.random.randint(1, 11, 4)
print(a)
print(b)
print(np.dot(a, b))

[[7 7 6 2]
 [8 2 8 6]
 [4 2 3 2]]
[8 8 3 2]
[134 116  61]


11.	Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [21]:
a = np.random.random((2, 3))
b = np.random.random(3)
print(a)
print(b)
print(np.dot(a, b))

[[0.69196085 0.41741987 0.56604703]
 [0.47076984 0.93024924 0.81009399]]
[0.17077535 0.00446573 0.75418285]
[0.5469369  0.69550911]


12.	Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [22]:
a = np.random.randint(1, 11, (2, 2))
b = np.random.randint(1, 11, (2, 2))

print(a)
print(b)
print(a * b)

[[10  6]
 [ 9 10]]
[[1 1]
 [9 2]]
[[10  6]
 [81 20]]


13.	Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [23]:
a = np.random.randint(1, 11, (2, 2))
b = np.random.randint(1, 11, (2, 2))

print(a)
print(b)
print(np.dot(a, b))

[[2 4]
 [8 3]]
[[8 9]
 [9 2]]
[[52 26]
 [91 78]]


14.	Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [27]:
a = np.random.randint(1, 101, (5, 5))

print(a)

print(np.sum(a))


[[35 57 17 85 85]
 [ 3 33 50 44 51]
 [68  9 26 33 80]
 [97 38 53 35 99]
 [63 77 28 86 89]]
1341


15.	Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [28]:
a = np.random.randint(1, 11, (4, 4))
b = np.random.randint(1, 11, (4, 4))

print(a)
print(b)
print(a - b)

[[ 6  4  6 10]
 [ 4  4 10  1]
 [ 2  9  6  1]
 [ 4  6  9  2]]
[[ 4  4  8  1]
 [ 3  3  3  9]
 [ 8  4  3  9]
 [ 6  4  1 10]]
[[ 2  0 -2  9]
 [ 1  1  7 -8]
 [-6  5  3 -8]
 [-2  2  8 -8]]


16.	Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [35]:
a = np.random.random((3, 3))
print(a)

print(sum(a.T))

[[0.52884967 0.21277685 0.86895704]
 [0.87941387 0.12641138 0.49203855]
 [0.48851359 0.51478871 0.64712441]]
[1.61058357 1.4978638  1.65042671]


17.	Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [40]:
a = np.random.randint(1, 11, (3, 4))
a_sq = a ** 2
print(a)
print(a_sq)

[[ 4  6  4 10]
 [ 3 10  5  8]
 [ 6 10  5 10]]
[[ 16  36  16 100]
 [  9 100  25  64]
 [ 36 100  25 100]]


18.	Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [43]:
a = np.random.randint(1, 11, 4)
a_sq_root = a ** 0.5
print(a)
print(a_sq_root)

[7 4 4 5]
[2.64575131 2.         2.         2.23606798]
